hardware_interface:
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    - gripper_joint
  sim_control_mode: 0
generic_hw_control_loop:
  loop_hz: &loop_rate 100
  cycle_time_error_threshold: 0.015
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_rate
gripper_controller:
  type: position_controllers/JointTrajectoryController  
  joints:
    - gripper_joint
whole_body_controller: &whole_body_controller
  type: position_controllers/JointTrajectoryController  
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
whole_body_controller/body: *whole_body_controller
